### ISSUE TITLE
Remove FAQ, point to docs instead

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop.org#1024]
https://github.com/freedomofpress/securedrop-docs/pull/439 merged the relevant contents from the FAQ into the main documentation.

We should now be in a good position to remove the FAQ link from the menu and point to the docs instead:

- [ ] Promote latest docs version to stable
- [ ] Edit [menu](https://securedrop.org/admin/snippets/menus/menu/edit/2/) to point to docs instead of FAQ
- [ ] Unpublish FAQ pages and change slugs so we can redirect them
- [ ] Set up [redirects](https://securedrop.org/admin/redirects/) (can be done in Wagtail)

**Comment by eloquence** [comment]
@nathandyer Let me know if I missed any steps - I know this is not in our current dev cycle so leaving it up to Kev if we want to pull it in off-sprint.

**Comment by zenmonkeykstop** [comment]
If ye are happy with latest changes, I'm down with pulling this into this cycle as an off-sprint task. We're doing pretty well so far progress-wise (touch wood).

**Comment by nathandyer** [comment]
I put together this table which should be a comprehensive list of all the necessary redirects:

Original Link | Redirects To:
-- | --
https://securedrop.org/faq/about-securedrop/ | https://docs.securedrop.org/en/stable/what_is_securedrop.html
https://securedrop.org/faq/getting-securedrop-faq/ | https://docs.securedrop.org/en/stable/what_is_securedrop.html#operation
https://securedrop.org/faq/getting-onion-name-your-securedrop/ | https://docs.securedrop.org/en/stable/admin/deployment/onion_name.html
  |  
https://securedrop.org/faq/about-securedrop/#what-is-securedrop | https://docs.securedrop.org/en/stable/what_is_securedrop.html#what-is-securedrop
https://securedrop.org/faq/about-securedrop/#what-technologies-does-securedrop-use | https://docs.securedrop.org/en/stable/what_is_securedrop.html#technology
https://securedrop.org/faq/about-securedrop/#how-does-securedrop-work | https://docs.securedrop.org/en/stable/what_is_securedrop.html#how-it-works
https://securedrop.org/faq/about-securedrop/#what-type-of-information-does-securedrop-log | https://docs.securedrop.org/en/stable/what_is_securedrop.html#privacy
https://securedrop.org/faq/about-securedrop/#what-problems-does-securedrop-attempt-to-solve | https://docs.securedrop.org/en/stable/what_is_securedrop.html#purpose
https://securedrop.org/faq/about-securedrop/#how-is-securedrop-audited | https://docs.securedrop.org/en/stable/what_is_securedrop.html#audits
https://securedrop.org/faq/about-securedrop/#what-makes-securedrop-unique | https://docs.securedrop.org/en/stable/what_makes_securedrop_unique.html
https://securedrop.org/faq/about-securedrop/#does-securedrop-promise-100-security | https://docs.securedrop.org/en/stable/what_is_securedrop.html#security
https://securedrop.org/faq/about-securedrop/#who-created-securedrop | https://docs.securedrop.org/en/stable/what_is_securedrop.html#project-history
https://securedrop.org/faq/about-securedrop/#how-can-i-contribute-to-securedrop | https://docs.securedrop.org/en/stable/index.html#get-involved
  |  
https://securedrop.org/faq/getting-securedrop-faq/#how-can-media-organizations-install-securedrop | https://docs.securedrop.org/en/stable/what_is_securedrop.html#planning-preparation
https://securedrop.org/faq/getting-securedrop-faq/#what-type-of-hardware-is-needed-to-run-securedrop-and-how-much-does-it-cost | https://docs.securedrop.org/en/stable/what_is_securedrop.html#cost
https://securedrop.org/faq/getting-securedrop-faq/#what-types-of-attributes-are-required-for-a-securedrop-sysadmin | https://docs.securedrop.org/en/stable/admin/reference/admin.html
https://securedrop.org/faq/getting-securedrop-faq/#how-does-securedrop-interact-with-an-existing-corporate-network | https://docs.securedrop.org/en/stable/what_is_securedrop.html#environment-overview
https://securedrop.org/faq/getting-securedrop-faq/#what-is-required-for-the-securedrop-landing-page | https://docs.securedrop.org/en/stable/admin/deployment/landing_page.html
https://securedrop.org/faq/getting-securedrop-faq/#how-long-does-setup-and-training-take | https://docs.securedrop.org/en/stable/training_schedule.html
https://securedrop.org/faq/getting-securedrop-faq/#can-you-use-securedrop-with-multiple-journalists | https://docs.securedrop.org/en/stable/what_is_securedrop.html#sharing-access
https://securedrop.org/faq/getting-securedrop-faq/#can-you-share-securedrop-with-different-organizations | https://docs.securedrop.org/en/stable/what_is_securedrop.html#sharing-access
https://securedrop.org/faq/getting-securedrop-faq/#what-type-of-lifecycle-support-does-fpf-provide | https://docs.securedrop.org/en/stable/getting_support.html
  |  
https://securedrop.org/faq/getting-onion-name-your-securedrop/#what-are-onion-names | https://docs.securedrop.org/en/stable/admin/deployment/onion_name.html#what-are-onion-names
https://securedrop.org/faq/getting-onion-name-your-securedrop/#how-do-onion-names-work | https://docs.securedrop.org/en/stable/admin/deployment/onion_name.html#how-they-work
https://securedrop.org/faq/getting-onion-name-your-securedrop/#will-onion-names-continue-to-work-years-from-now | https://docs.securedrop.org/en/stable/admin/deployment/onion_name.html#how-they-work
https://securedrop.org/faq/getting-onion-name-your-securedrop/#how-do-i-get-an-onion-name | https://docs.securedrop.org/en/stable/admin/deployment/onion_name.html#getting-an-onion-name
https://securedrop.org/faq/getting-onion-name-your-securedrop/#if-i-register-an-onion-name-can-i-still-use-the-full-length-onion-address | https://docs.securedrop.org/en/stable/admin/deployment/onion_name.html#does-this-replace-the-original-address
https://securedrop.org/faq/getting-onion-name-your-securedrop/#can-i-list-only-the-onion-name-on-the-landing-page-to-keep-it-simple-or-should-i-also-list-the-full-v3-address | https://docs.securedrop.org/en/stable/admin/deployment/onion_name.html#does-this-replace-the-original-address
https://securedrop.org/faq/getting-onion-name-your-securedrop/#how-do-i-update-the-onion-address-associated-with-an-onion-name | https://docs.securedrop.org/en/stable/admin/deployment/onion_name.html#updating-an-onion-name
https://securedrop.org/faq/getting-onion-name-your-securedrop/#would-freedom-of-the-press-foundation-ever-revoke-my-organizations-onion-name | https://docs.securedrop.org/en/stable/admin/deployment/onion_name.html#revoking-onion-names
https://securedrop.org/faq/getting-onion-name-your-securedrop/#how-do-i-contact-the-securedrop-team | https://docs.securedrop.org/en/stable/getting_support.html

**Comment by nathandyer** [comment]
I've taken care of the first two items in the list:

* [x]  Promote latest docs version to stable
* [x]  Edit [menu](https://securedrop.org/admin/snippets/menus/menu/edit/2/) to point to docs instead of FAQ
* [ ]  Unpublish FAQ pages and change slugs so we can redirect them
* [ ]  Set up [redirects](https://securedrop.org/admin/redirects/) (can be done in Wagtail)

**Comment by eloquence** [comment]
Looks great, thank you! Can you check if you're able to access https://securedrop.org/admin/redirects/? If so I think you should be able to create the redirects directly from there :)

**Comment by nathandyer** [comment]
Thanks @eloquence, I wasn't sure if I was OK to do the redirects myself or not. I can confirm I was able to access it, and have added them in. Just to note, it looks like Wagtail doesn't allow for us to redirect at the jumplink level. If you know of a way to make that work, please let me know, otherwise I think we are OK given that the previous slugs all have redirects in place that will take folks to the right areas in the documentation.

* [x]  Promote latest docs version to stable
* [x]  Edit [menu](https://securedrop.org/admin/snippets/menus/menu/edit/2/) to point to docs instead of FAQ
* [x]  Unpublish FAQ pages and change slugs so we can redirect them
* [x]  Set up [redirects](https://securedrop.org/admin/redirects/) (can be done in Wagtail)

**Comment by eloquence** [comment]
Since fragments don't get sent to the server (the browser just attempts to jump to the same fragment at the target URL), I think the only reliable solution to preserving those would be to add identical fragments at the relevant targets. I don't think that's worth doing, especially since those are likely to change over time and would be a pain to maintain. So I think we can call this done - thanks, Nathan!
