### ISSUE TITLE
Broken Link in Navigation Menu

### ISSUE THREAD

**Issue by dkvc** [freedomofpress/securedrop.org#1057]
The "Install SecureDrop" link in [SecureDrop website](https://securedrop.org) navigation menu is broken. It is currently linked to "[https://docs.securedrop.org/en/stable/overview.html](https://docs.securedrop.org/en/stable/overview.html)".

It should either be removed or changed to another link (can't find any specific link for single installation).

**Comment by zenmonkeykstop** [comment]
Thanks for letting us know @dkvc - we recently reorganized our documentation and missed this! Should be fixed now.

**Comment by harrislapiroff** [comment]
Resolved in content
