### ISSUE TITLE
SecureDrop Directory Form Expects Protocol in URL Field

### ISSUE THREAD

**Issue by nathandyer** [freedomofpress/securedrop.org#1070]
When filling out the [SecureDrop Directory form](https://securedrop.org/directory/submit/), there are required fields that ask for a URL. If someone decides to type out the address by hand, but leaves out the protocol (http/https), it doesn't allow the form to be submitted, and instead returns back and asks the user to "Please enter a URL."

We should remove this requirement to include the protocol, since most folks don't include that if they are manually typing the address.

**Comment by eloquence** [comment]
@nathandyer You could change the type in the form for all URLs to "single-line text". The only benefit of the URL type _is_ the validation, so if that's causing users confusion, we might as well avoid it.

**Comment by nathandyer** [comment]
@eloquence That makes sense, I went ahead and changed the type to "single-line text" for the organization URL and landing page URL (but left the "URL" type for the image URL, since we do need to confirm a full path there). I submitted it for moderator approval just to make sure I'm not accidentally breaking something further down the line. Once that's approved, I think we can close this issue.

**Comment by eloquence** [comment]
LGTM! If folks struggle with the image URL field still we can always tweak that as well.
