### ISSUE TITLE
Need a better list of languages link on securedrop.org

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop.org#1093]
The "21 languages" link on https://securedrop.org/ used to point to a list of languages in the docs, looks like that got lost in content reorg - if we still have the list somewhere, we should update the link, otherwise we can (with teary eye emoji) remove it for now.

**Comment by cfm** [comment]
As of freedomofpress/securedrop-docs#503, the documentation itself just
links to
<https://github.com/freedomofpress/securedrop/blob/develop/securedrop/i18n.rst>.
We decided that was sufficiently administrator-friendly, but I realize
we might not think it's equally public-friendly....

**Comment by eloquence** [comment]
I think it'll do for now, thanks. :) I've updated it. (The count includes English, hence one more than in the file.)
