### ISSUE TITLE
Prolific 404s at redirects

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/securedrop.org#1097]
We're noticing a bunch of 404s endpoints that _do exist but with a trailing slash_

![image](https://github.com/freedomofpress/securedrop.org/assets/296631/c71ca8a1-b125-44e6-90d2-99b980ab1947)

My theory is that something in the latest django upgrade is causing these to get logged before django redirects them to their trailing slash counterparts.

**Comment by chigby** [comment]
My best guess is that this is on account of `RequestLogMiddleware` coming _after_ `django.middleware.common.CommonMiddleware` ([see docs](https://docs.djangoproject.com/en/4.2/ref/middleware/#django.middleware.common.CommonMiddleware)). I'm not sure what, if anything, changed between Django 3.2 and 4.2 to cause this, but it seems like we can fix this by moving `RequestLogMiddleware` "higher" than `CommonMiddleware`. Locally, this gives me the correct status code in the logs, which is 301.

**Comment by harrislapiroff** [comment]
Let's dupe this ticket across other web repos
