### ISSUE TITLE
Commands to run when starting from a blank database

### ISSUE THREAD

**Issue by raq929** [freedomofpress/securedrop.org#153]
@conorsch @msheiny I'm just putting these somewhere so we all have a list. Probably should move t o documentation at some point.
`createresultgroups` - creates all the text associated with results
`createnavmenu` - creates the nav menu and some of the index pages if the don't exist yet
`createfootersettings` - creates all the text that goes in the footer

These do not create any dev data, just basic things like menus and buttons, etc.

**Comment by harrislapiroff** [comment]
This is now documented in the README and also the commands are different than they were in 2017 😆
