### ISSUE TITLE
Expand functional testing for json logging to catch CF events

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop.org#482]
@harrislapiroff wrote awesome tests in #472 that address unit testing concerns I had. 

The more I was digging tho ... @kushaldas + @harrislapiroff both helped me realize that we need a stronger story for e2e functional log testing to make sure the log settings havent broken. 

We currently have some of that implemented under `molecule` + `testinfra` in a rather hacky way but I'd like to do that at a deeper level so we can also catch things like cloudflare logs to ensure they get dumped to our log file in json format.

Scope of this ticket is specifically to ensure cloudflare logs are dumping to json file .. but i expect this ticket will setup the scaffolding for later expansion into other logging events we want to ensure are hitting disk.

**Comment by harrislapiroff** [comment]
[Backlog pruning 5/10] Our logging has changed a lot since this issue was opened. Closing as stale and someone can reopen in Infra if needed.
