### ISSUE TITLE
Form pages show an empty red warning box when no value is given for the warning box

### ISSUE THREAD

**Issue by edenemmanuel** [freedomofpress/securedrop.org#551]
## Bug

Form pages show an empty red warning box when no value is given for the warning box.

### Steps to reproduce
1. Create a Form page in the SecureDrop.org Wagtail interface
2. Create a Form page as usual, but skip the Warning section.
3. Preview the page to see something like below.

### Actual behavior

![screenshot from 2018-10-02 16-43-10](https://user-images.githubusercontent.com/8506155/46382900-46b28780-c662-11e8-9dfa-651be28bd619.png)

### Expected behavior

If no warning text is given, I expect no empty warning box to show.

### User stories
As a form designer, I might not necessarily want to throw a scary warning, especially if it's a survey for a speciic group of people.

As a survey participant, seeing a red box (or a warning) might potentially reduce my cognitive capacity to fill out the survey effectively.

**Comment by eloquence** [comment]
This bug is back with the new Wagtail version. Steps to reproduce:

1. Create a new  "Form" type page on SecureDrop.org
2. Press "Preview"

Expected result:
- No red banner of doom

Actual result:
- Red banner of doom is back
