### ISSUE TITLE
Upgrade to python 3.7

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop.org#568]
SSLyze (used by pshht) has a hard requirement for Python >=3.6. Currently we use Python 3.5.3 for SecureTheNews. Because these dependencies are highly coupled, it will make updating them difficult as time goes by.

We are also far behind on pshtt version https://github.com/freedomofpress/securedrop.org/blob/master/dev-requirements.txt#L56 (latest as of this writing is 0.5.2)

Recently there have been several security fixes for SSL-related libraries. While they do not directly affect SecureTheNews, they will make upgrades more complex should a rapid version be required.

Let's move to Python 3.6 to ensure we can timely update dependencies, should a security vulnerability require rapid patching.

**Comment by conorsch** [comment]
Updated issue to frame as ask for Python 3.7. We're still using Python3.5: 

https://github.com/freedomofpress/securedrop.org/blob/develop/devops/docker/ProdDjangoDockerfile#L23-L24

Now that the app is fully containerized, we can move to 3.7 by bumping the value in that Dockerfile. The concerns above related t pshtt & sslyze are currently blockers for updating to Python 3.8, last I checked. Let's get to 3.7 and go from there, engaging upstream as required.
