### ISSUE TITLE
Support images in Form fields

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop.org#627]
In the context of longer surveys like the SecureDrop user survey (see page ID `170` for current draft), it would be helpful to be able to directly include images with some questions, so that we can explain concepts by using screenshots, rather than by using text alone. 

The survey question about SecureDrop's "Flag for Reply" workflow is a good example: the workflow is very difficult to explain, but if the user has seen it before, a screenshot will likely bring back fond memories.

**Comment by eloquence** [comment]
@ninavizz helpfully put together a mockup of what this could look like. Click the first "Show Screen" on this page:

https://projects.invisionapp.com/share/6YSDI4I5NM8#/screens/367268791

Harris, I'm sure you can see the arguments for a lightbox like this (even if it's an image-only overlay) in terms of clutter and cognitive load. For a first iteration though even inline display of images alongside the questions would be a great start.

**Comment by harrislapiroff** [comment]
Resolved as part of #628
