### ISSUE TITLE
Fold in a tor hidden service and tor proxy container into dev/ci

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop.org#63]
This is needed particularly for the tor hidden service detection logic (see #62) and would ease development/testing without requiring a bunch of manual user steps.

**Comment by sssoleileraaa** [comment]
[Backlog grooming 5/10] @eloquence - Now that all our websites have tor services, has the Infra team already developed a way to do this automated testing?

**Comment by eloquence** [comment]
Closing out as under-specified/stale.

**Comment by msheiny** [comment]
Stale!? This ticket seems delicious 😋

**Comment by harrislapiroff** [comment]
@msheiny you gotta come back here and reopen it ;)
