### ISSUE TITLE
Replace "Forbes" in HP's feature blob

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop.org#646]
...cuz it's no longer in the SD Directory. #doh

I'd love to nominate AlJazeera, as an excellent newsroom with international cred and that is localized in a non-English alphabet language?

More broadly tho, it'd be nice to perhaps more thoughtfully curate a set of newsrooms for this blob, around some specific product marketing/positioning objectives? Apologies if use of the MBA `douchejargon` is offensive; but I do think it'd be neat to more intentionally speak to prospective newsrooms/NGOs, with site content.

Immediate purpose of this issue, is just to remove the Forbes bit, tho. It wouldn't be a Nina Issue if I didn't inject a little aspiration-creep into it, now would it?

![image](https://user-images.githubusercontent.com/8262612/64318258-866aa900-cf6e-11e9-8061-56d6efa5ea10.png)

**Comment by eloquence** [comment]
Good catch, for now I've replaced the two ones that have been delisted (AP and Forbes) with WaPo and Al Jazeera. (The Forbes SecureDrop is back up and may get re-listed soon.)
