### ISSUE TITLE
Link to contact form instead of email address for notifying FPF about onion URL mismatches

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop.org#648]
Directory entries currently state:

> If you encounter a mismatch, please contact us at securedrop@freedom.press. This could be evidence of an attempted attack, or it could be a simple failure to communicate between an organization running SecureDrop and Freedom of the Press Foundation. In either case, we will investigate the matter and establish a path to resolution. 

We should not be linking to the email address here and instead point to the contact form. That's because prospective sources may be using this address, and email is less secure by default than a form submission via an HTTPS website.

NB: The current https://securedrop.org/help/ form is geared towards news organizations; it may be good to prepare a variant that's not.

**Comment by eloquence** [comment]
I've created https://securedrop.org/report-an-error/ specifically for reporting errors, but note that it should not be considered ready for prod use until #554 is resolved or we've whitelisted it, to avoid CSRF errors on submissions.

Any suggestions on the form itself more than welcome :)

**Comment by prateekj117** [comment]
@eloquence Looks like #554 is resolved. I can start working on linking the new form on the directory page.

**Comment by eloquence** [comment]
@prateekj117 That's some good issue archaeology! Yes, it looks like the form is being handled correctly without additional whitelisting, based on some quick testing. Would definitely be great to get a PR for this, thank you :)

**Comment by prateekj117** [comment]
@eloquence I think I am missing something here. I cannot find the code for the `contact-form` page and the new `report-an-error` page in the source code.

**Comment by harrislapiroff** [comment]
Both forms are instances of [`FormPage`](https://github.com/freedomofpress/securedrop.org/blob/master/forms/models.py#L44). The necessary content change here should be in [this template](https://github.com/freedomofpress/securedrop.org/blob/4b4f267192a57ba519a7e167f44b98108112fe58/directory/templates/directory/_instance_instructions.html). The right approach is probably to add a foreign key `report_error_page` to [`DirectorySettings`](https://github.com/freedomofpress/securedrop.org/blob/b91e1d586db01c5171d567f6d6da2ecc0e8eaff9/directory/models/settings.py#L11) to be used in the template. let me know if you have any questions!
