### ISSUE TITLE
Clarify "Suppress Referrers" language

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop.org#649]
As a non-technical user, I have no idea what this means—yet it is presented to me in what appears to be an alarming "this is risky" kind of presentation. Linking out to a policy page for developers, obfuscates the message even further. 

Ahead of deeper Source Journey types of things, I'd like to see this message edited to clearly convey the following, and in non-technical terms:
1. **Direct Action:** What does the user need to DO? In active-voice.
   - Is the house engulfed in flames? —> Leave!
   - Is one room on fire? —> Call 911
   - Is there a trash can filled with kleenex dangerously close to a heated oven? —> Move the can
    - OMGWTF!!! —> scream and wave arms around and panic, but effectively do nothing
2. **Explain Why:** WHY should the user care?
   - Are people going to die?
   - Will property be destroyed?
   - Are you about to be mightily inconvenienced?
   - Do I just think something I geek about is a priority, that you really won't care about?
3. **Cite Consequences:** WHAT are the implications, if they don't?
   - Your life will be changed forever
   - Your life will suck mightily for about a year
   - You will lose an afternoon's work
   - I'll be upset, but really you won't notice a thing.
4. All, **free of jargon**. Which Nina can help with, but confusion only amplifies anxiety; and imposter syndrome just generally sucks.

![image](https://user-images.githubusercontent.com/8262612/65174887-a1c1c380-da06-11e9-97d3-c9604501d9c0.png)
P.S.: I _was_ using Tor browser, when I saw this message... so, there's also that. :D

**Comment by rocodes** [comment]
See #637

**Comment by eloquence** [comment]
Closed as duplicate (but please feel free to copy language over to the other issue as warranted).
