### ISSUE TITLE
Sporadic Internal Server Error on saving draft

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop.org#653]
While editing https://securedrop.org/news/advisory-november-2019-intel-vulnerabilities/
(now published), I encountered sporadic "Internal Server Errors" (just the headline on white background, no other page content) after saving drafts. The saves seemed to go through anyway. I've not been able to reproduce with fresh drafts.

**Comment by conorsch** [comment]
@eloquence Have you seen this recently? Given the move to containers on the backend, I don't think the original report is still relevant, but let's keep it open if the behavior is at all spotty.

**Comment by eloquence** [comment]
Nope, I've not encountered this in forever. I think it's gone :crossed_fingers: , closing :)
