### ISSUE TITLE
Remove references to The New Yorker in our overview

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop.org#669]
From https://securedrop.org/overview/:

SecureDrop is an open source whistleblower submission system news organizations can install to safely and anonymously receive documents and tips from sources. It is used at over 50 news organizations worldwide, including _The New York Times, The Washington Post, ProPublica_, _The New Yorker_, and _The Intercept_. 

Since the New Yorker is not actively using SecureDrop, we should replace references to them with an active instance.

**Comment by eloquence** [comment]
@rocodes I think you can edit this with your existing permissions, can you check?

**Comment by rocodes** [comment]
yes - submitted draft for moderation/approval

**Comment by eloquence** [comment]
LGTM, published :)
