### ISSUE TITLE
store URL of news organization main domain

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop.org#675]
We have some SecureDrop instances that have their landing pages hosted on a subdomain or a different domain. It would be useful to:

* add the `organization_url` to the directory model
* expose via `https://securedrop.org/api/v1/directory/`
* add as field to the [instance verification form](https://securedrop.org/directory/submit/)
* (once deployed) manually add it for existing organizations since there are a small number

A couple of examples:
* The Center for Public Integrity's landing page for sources is available at apps.publicintegrity.org, but their main website is publicintegrity.org
* SF Chronicle has their landing page on projects.sfchronicle.com but their main domain is sfchronicle.com

While these examples are using subdomains, iirc we've had examples where the landing page has been hosted on a different domain (I vaguely recall a GitHub-hosted landing page). 

One motivation for this is for programmatically generating `publicintegrity.org.securedrop.tor.onion` -> `<blah>.onion` URL mappings (ref: https://github.com/freedomofpress/securedrop/issues/3668)

**Comment by eloquence** [comment]
@redshiftzero is the address schema intended to include the domain name of the organization's website, or would an address like `theintercept.securedrop.tor.onion` also work? If that approach would work for you and Tor, we can enforce the uniqueness of such IDs on our end. IMO they would have the benefit of being more memorable, but I understand if that if it clashes with intended standardization towards partial or fully qualified domain names, it may not be an option.

**Comment by redshiftzero** [comment]
My intention with this issue is to track the main domain of the news organization (i.e. `https://www.nyworld.com/`). We would eventually want to also add an additional field `httpse_url` to track what the onion URL will get rewritten to (`nyworld.securedrop.tor.onion`) since I don't think we'd want to reuse `onion_address`. For now we don't need the `httpse_url` field yet (well, if we stay with the URL scheme in the next paragraph) since we won't be encouraging news organizations to advertise these addresses until the functionality on Tor/HTTPSE's side stabilizes. 

Regarding the naming scheme itself for `httpse_url`, I don't love the `.com` in `nyworld.com.securedrop.tor.onion` but my reasoning was without the `.com`, there is not a clear mapping from the existing URL space. This seems bad both for us (unless we manually resolve conflicting URLs, e.g. if `abc.net.au` were to beat `abc.es` to the `abc.securedrop.tor.onion` URL) and possibly in the future for sources, who may discover SecureDrop instances via these URLs (we don't want a source to submit to `abc.securedrop.tor.onion` thinking that they are submitting to `abc.es`). I think a source being able to just append `securedrop.tor.onion` to the news organization's web URL and get to their SecureDrop is nice. With that said this URL scheme is not set in stone and is one of the main items to discuss and decide upon when we do a second iteration of the ruleset in the next sprint.

**Comment by eloquence** [comment]
Per discussion at web sync today we can treat this feature as blocked pending further specification as a result of an initial, manually conducted pilot deployment with a handful of newsrooms, and newsroom feedback coming out of said pilot outreach.

**Comment by eloquence** [comment]
We settled on using a schema like `theintercept.securedrop.tor.onion` where the fully qualified domain name is not used, but it would still be useful to store the organization's main domain, so that we can use it as the `primary_domain` for lookup purposes in https://github.com/freedomofpress/securedrop-https-everywhere-ruleset/blob/main/onboarded.txt (which is used to generate the rulesets).

This issue is already well-specified and should be considered unblocked ready for development as in the issue description; as stated there, we can manually populate the existing directory entries.

**Comment by chigby** [comment]
Blocked until #722 is deployed

**Comment by eloquence** [comment]
The `organization_url` is currently not exposed in the editor view. In order to resolve this issue, we'll need to add it to the editor for directory entries so that historical data can be backfilled by hand. Unassigning myself until then.

**Comment by eloquence** [comment]
This is done for all live directory entries. You can view the results (with `curl` and `jq` installed) via:

```bash
$ curl -s https://securedrop.org/api/v1/directory/?format=json | jq '.[] | {title,organization_url,onion_address}'
```

I've also added a new `Organization URL` field to the directory submission form:

https://securedrop.org/directory/submit/

Closing this issue, but review/suggestions for any changes welcome.
