### ISSUE TITLE
Update Logos

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop.org#692]
## Problem
In 2019 the logos were given a polish, and subsequently need to be updated across the site. [This is the ticket](https://github.com/freedomofpress/securedrop-ux/issues/71) for the design work in the UX repo, for reference. 

## Solution
This ticket is for implementation and to manage delivery/iteration of art assets.

**Comment by ninavizz** [comment]
Inserting comment as FYI note per the updated branding of SD... there is now different art for the solid logo, rendering at small vs big sizes. Differences are highlighted in yellow, in the below PNG. 

![logo_differences](https://user-images.githubusercontent.com/8262612/82486565-ecae4200-9a91-11ea-8076-8699d2148d9e.png)

**Comment by ninavizz** [comment]
FYI, in the SD Repo ticket, @eloquence made the below comment:

> Trying the SVG, just a note that the SVG dimensions for this file are currently significantly smaller than the existing logo, so it just renders it as a tiny image in the existing location. Am resizing manually, will need to poke a bit more to ensure it fits snugly into its hexagon space.

This raised an excellent flag that is important to note to one and all: the udpated logo is now, no longer, a perfect hexagon. The logo updates presumed a majority of uses on solid backgrounds. For that, it helped to the logo is often used in a web of hexagons; the 2019 retreat tee and the Website, primary examples. For that, there is an alternate version, that I will include as final art, here. 

Just another FYI flag to the team, as we have yet to get the branding schema documented. See yellow bit identifying the delta, on the top of the color logo to the left.

![NotSquare](https://user-images.githubusercontent.com/8262612/82494505-87ad1900-9a9e-11ea-9f57-907e61b2f84e.png)

**Comment by ninavizz** [comment]
Transparent logo art for the homepage hero module, and for the global footer. Lemme know if it fits, @harrislapiroff! Up next, the header "knockout" logo, and then the favicon.

[BigTransparent.zip](https://github.com/freedomofpress/securedrop.org/files/4659181/BigTransparent.zip)

**Comment by ninavizz** [comment]
Small/Solid logo, for the flexbox header. 
[SmallSolid.zip](https://github.com/freedomofpress/securedrop.org/files/4659352/SmallSolid.zip)

Note: in the below screenshot, it gives a wacky dimension for the height. The ones I created here, are `40x45`

![image](https://user-images.githubusercontent.com/8262612/82498552-0a38d700-9aa5-11ea-92c0-ff8b8cf8825e.png)

**Comment by harrislapiroff** [comment]
Thanks for all this @ninavizz! We'll get on these changes

**Comment by ninavizz** [comment]
For the Favicon, let's use the same one the product itself was updated to have, a few months ago. Below is a screenshot... the favicon asset should exist in the SD repo, somewhere. 

![image](https://user-images.githubusercontent.com/8262612/82596162-b89f5380-9b5b-11ea-9068-945aaa8a5f44.png)

**Comment by harrislapiroff** [comment]
Sounds great @ninavizz! Happy to defer to your judgment here, but one thought I have is I wonder if we should alter the favicon at all to provide a subtle clue as to whether you're looking at the website or a SecureDrop instance? (Particularly in the maybe rare instance that someone has both open?)

I'm thinking something like what Slack does (though I don't actually love this particular implementation... y so square?) to distinguish between their marketing site and a Slack organization:

![image](https://user-images.githubusercontent.com/296631/82600201-8b629d80-9b7b-11ea-8f80-e70d23bae32d.png)

(Just a thought! Not attached to it.)

**Comment by ninavizz** [comment]
@harrislapiroff LOL... _siiiiiigh_ Erik and I spent around 3 weeks trying to accomplish that. The Cube is haard, though. I did sooo many versions over that time, trying to get _anything_ right. We never got anything looking comparably sweet like the 4-color logo, tho, so finally abandoned that ship. 

That said, I definitely do **not** see the door as closed. Please take a stab at it, if you'd like—where I left off, attached as a ZIP! I would so love to see a judo-brand-move pulled-off as Slack did, above. Just... not at the expense of your sanity. Sane Harris, first; judomove favicons, second. 

[SD Favicons — NEA.zip](https://github.com/freedomofpress/securedrop.org/files/4664555/SD.Favicons.NEA.zip)

**Comment by eloquence** [comment]
Is this fully actionable, or do we still need anything from @ninavizz to move this forward?

**Comment by chigby** [comment]
I started working on this and I didn't notice anything that seemed missing. I think it was just lowered in priority for tracker-related work.

**Comment by harrislapiroff** [comment]
Going to reopen until we actually deploy. @ninavizz please review on https://sandbox-upgrade.securedrop.org/ and let us know any changes you see need to be made!

**Comment by ninavizz** [comment]
Hi gang! Apologies for my lateness to the feedback-party. 

1. Logo not quite lining-up with hexagons surrounding it. I trust @harrislapiroff's wicked eye on proper alignment, tho. If misalignment is due to artwork funkiness, pls reach out—happy to modify! Seems like a slightly smaller size might do the trick, but I could also be wrong. Also, the top-right corner seems to be getting lopped, and there's a pixel or two of space to the left, along the neighboring hexagon's right edge. ??
![image](https://user-images.githubusercontent.com/8262612/91771903-a8563600-eb98-11ea-8d47-f87f07f0aaaa.png)

2. Header logo seems fuzzy. Perhaps use a PNG that is 3-400% of the 100% size, then displayed at 20-30%, if it needs to be a PNG? Also—pls to nudge logotype 3-5px closer to the logomark? Again, I trust Harris' wicked-eye on what feels right. If I need to generate this, pls to let me know; happy to do & post asap!
![image](https://user-images.githubusercontent.com/8262612/91772048-efdcc200-eb98-11ea-8d2d-a51b43fd5be5.png)

3. Footer logo looks great! Possibly a touch more transparent, like 10% more, but I'm imagining Erik grunt in disapproval at that. It just doesn't feel "intentionally" transparent, enough, is all.

**Comment by eloquence** [comment]
> Possibly a touch more transparent, like 10% more, but I'm imagining Erik grunt in disapproval at that. It just doesn't feel "intentionally" transparent, enough, is all.

I'd also like to see what it looks like with higher transparency. Intuitively I would prefer it to be not transparent at all, but perhaps part of the reason it looks a bit "broken" to me in the footer is, as you say, that it doesn't look fully intentional right now.
