### ISSUE TITLE
Add Twitter/Mastodon links to footer

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop.org#696]
We currently don't showcase our social links anywhere on securedrop.org. I suggest we add the following as icon links in the footer:
https://twitter.com/securedrop
https://fosstodon.org/@securedrop (new)

This is the recommended icon for Mastodon account: https://fontawesome.com/icons/mastodon

If we use `rel="me"` for the link, Mastodon will render our account as _verified_.  (See docs [here](https://docs.joinmastodon.org/user/profile/)).

**Comment by harrislapiroff** [comment]
Let's make these URLs settable via a site settings model and use this design:

![Artboard](https://user-images.githubusercontent.com/296631/89320168-233a3880-d64f-11ea-8a39-d3ff58aad24a.png)

**Comment by prateekj117** [comment]
@harrislapiroff Sounds good. I can have a look into this.

**Comment by eloquence** [comment]
@prateekj117 Let us know if you still want to take this on this week, otherwise we'll probably get to it in a few days :)

**Comment by prateekj117** [comment]
@eloquence I will be able to. So sorry I took it and remained inactive from quite some days without an update on already pending PRs and issues.

**Comment by prateekj117** [comment]
@eloquence @harrislapiroff I think I should add a new `MultiFieldPanel` named "Social Media" and add two links two field panels for now, for twitter or Mastodon. Sounds good?

**Comment by harrislapiroff** [comment]
@prateekj117 Yes, that sounds right!

**Comment by eloquence** [comment]
Sounds good. I think we can add http://microformats.org/wiki/rel-me to both those links; Twitter will ignore it, but Mastodon will interpret that microformat to indicate our Mastodon account as verified.

**Comment by prateekj117** [comment]
Cool.

**Comment by chigby** [comment]
The mastodon icon linked to on the Font Awesome website includes a notice that using it requires attribution and a link to the license, unless we have paid membership to Font Awesome. Is this the case, or is there a place on the website appropriate for properly attributing such things?

**Comment by eloquence** [comment]
According to https://fontawesome.com/license/free 

> Downloaded Font Awesome Free files already contain embedded comments with sufficient attribution, so you shouldn't need to do anything additional when using these files normally. 

This is true for the SVG version that's found in the ZIP file:
https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself

If we convert to PNG, we should preserve this attribution (we could use an HTML comment, for example).
