### ISSUE TITLE
Onion available button shows even when onion being used

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/securedrop.org#698]
The `onion-location` header added in #695 causes tor browser to render an Onion available button, which is great! Unfortunately it still renders the button _even if_ the onion is already being used.

We'll chat with Tor about whether this is a UI behavior issue, but, in the meantime, let's fix it for SDO by setting the `onion-location` header conditionally—only if the onion service is not being used. We expect that the onion url will be available to django as the hostname and we can use that to check.

**Comment by eloquence** [comment]
Upstream issue:
https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40028

I learned via a [tweet](https://twitter.com/DaneQuain/status/1281100332681101312) that Tor users are sent into an infinite reload loop if the "prioritize .onion: always" setting is enabled in Tor Browser. Unless upstream responds that a fix is on the way, I think that argues for prioritizing a fix on our side by suppressing `Onion-Location` when the onion service is loaded.

**Comment by harrislapiroff** [comment]
The current status of this issue is that infra has added a gateway-level modification to suppress this header when the application is accessed via onion url. I think we should handle this application-side as well (instead?). I believe that what should be necessary here is to add a conditional check to the middleware that the onion location does not match the current hostname before adding the header.

This is tricky to test locally, but might be doable by [setting up a hidden service on your local machine](https://community.torproject.org/onion-services/setup/). Are there any downsides to doing so?

**Comment by gusgustavo** [comment]
Hi friends, just to let you know that 40028 bug was fixed and is now available on Tor Browser 9.5.4 (stable).
https://blog.torproject.org/new-release-tor-browser-954

**Comment by eloquence** [comment]
Thanks @gusgustavo .

Closing as resolved upstream, and onion logic will be handled at the infra layer going forward.
