### ISSUE TITLE
"Pls use Tor" banner interferes with usability on mobile

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop.org#701]
The "You are not anonymous while using this browser" takes up the whole screen on mobile browsers, interfering with basic site usability. In Firefox/Tor mobile versions, it also renders incorrectly for me, with the "X" to close not visible without scrolling horizontally, making the site very difficult to use.

Moreover, the guidance is misleading on mobile: If you download the mobile version of Tor Browser, you will still get the banner (we don't recommend using mobile versions of Tor for actual SecureDrop submissions).

We should come up with more appropriate security guidance for mobile users, and consider a design that's less disruptive of other site uses.

**Comment by prateekj117** [comment]
@eloquence Will look into this.

**Comment by ninavizz** [comment]
The messaging for mobile should also be unique, as there are only 3rd party mobile apps for iPhones which may or may not be safe. Android has an official app from Google Play or FDroid.

**Comment by harrislapiroff** [comment]
Sounds like there's a couple problems to fix here:

1. a rendering issue where the banner is impossible to dismiss on certain mobile browsers
2. a more conceptual messaging issue where we should be offering a different message to mobile users (maybe even different messages to android vs iphone users)

Thanks for looking into 1, @prateekj117! Keep me posted on what you find; we'd like to resolve this fairly urgently. For 2, I'm going to open a separate ticket.

**Comment by eloquence** [comment]
> The messaging for mobile should also be unique

Agreed; we generally want to direct folks to desktop if they want to submit tips. I would suggest the following language:

> Have a document to share?
> 
> Follow these steps to protect your anonymity:
> 
> 1. Choose a safe location, not a work computer.
> 2. Download the desktop version of Tor Browser from https://www.torproject.org/
> 3. Launch Tor Browser and return to this site. You are are now anonymous online.

This is an oversimplification but better than what we have now. It should be shown for mobile user agents, including mobile versions of Tor Browser.

**Comment by ninavizz** [comment]
@eloquence I want to be sensitive to the reality that many disadvantaged folks don't have laptops; nor, access to them. It feels restrictive and problematic to not acknowledge Tor Mobile options in any capacity.

**Comment by eloquence** [comment]
> @eloquence I want to be sensitive to the reality that many disadvantaged folks don't have laptops; nor, access to them. It feels restrictive and problematic to not acknowledge Tor Mobile options in any capacity.

I understand that concern but we cannot address it in this context. Our consistent advice to users has been to use the desktop version of Tor Browser, because we understand its security properties very well. If we want to support whistleblowers who only have access to mobile devices, there's a lot more work we have to do to understand the associated threat model, and that won't be done before this issue is resolved.

**Comment by ninavizz** [comment]
> I understand that concern but we cannot address it in this context. Our consistent advice to users has been to use the desktop version of Tor Browser, because we understand its security properties very well. If we want to support whistleblowers who only have access to mobile devices, there's a lot more work we have to do to understand the associated threat model, and that won't be done before this issue is resolved.

That's helpful to understand! Could we then clearly state that _for security reasons_ we discourage use of mobile browser use with Tor compatible apps?

**Comment by eloquence** [comment]
> Could we then clearly state that for security reasons we discourage use of mobile browser use with Tor compatible apps?

SGTM, but I think we will want to show the same message to mobile users regardless of whether they're currently using Chrome for Android, Safari for iOS, Tor for Android, Orfox, or whatever. Want to propose a tweaked version of the above language?

**Comment by prateekj117** [comment]
@eloquence @harrislapiroff I cannot replicate this issue in the mobile view of desktop version of Firefox/Tor. But I did face it on the mobile version of the same browsers. But due to the incompatibility of versions of my Desktop Firefox and Android Firefox, I am not able to perform `Remote Debugging` for now. :disappointed: I would appreciate it if someone else can take this issue for now.

**Comment by harrislapiroff** [comment]
@prateekj117 Thanks for your research! Very helpful. I'll take a look at this soon.

**Comment by harrislapiroff** [comment]
@SaptakS When you're online next, if you can look at this, that would be great.
