### ISSUE TITLE
Add .idea to gitignore

### ISSUE THREAD

**Issue by prateekj117** [freedomofpress/securedrop.org#705]
We should also add `.idea` to `.gitignore` as it is used by Jetbrains IDE for storing project-specific settings of a local environment.

**Comment by eloquence** [comment]
@prateekj117 By all means, please submit a PR to that effect. We don't use Jetbrains, but if it helps you, we're happy to merge.

**Comment by prateekj117** [comment]
@eloquence Yup. I use Jetbrains usually. Though I am curious about what you people prefer?
