### ISSUE TITLE
Update wagtail in dev-requirements

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/securedrop.org#713]
Looks like we have 2.7.4. in requirements.txt, but 2.7.3 in dev-requirements.txt for some reason—causing safety failures.

**Comment by prateekj117** [comment]
@harrislapiroff Yup. Should I simply just update the version in `dev-requirements.txt`?

**Comment by harrislapiroff** [comment]
I think you will actually want to use our [dependency management makefile commands](https://github.com/freedomofpress/securedrop.org#dependency-management) or, if those don't work, debug why not. Thanks!

**Comment by prateekj117** [comment]
@harrislapiroff Sure will do that. :+1:

**Comment by harrislapiroff** [comment]
@prateekj117 Thanks for offering to take this one on. I asked @SaptakS to complete it since we wanted to get it done quickly, though!
