### ISSUE TITLE
Add landing page scan results to API

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop.org#734]
In #527 we added a `manage.py` command that exports the landing page scan results in CSV format, which is handy for quickly determining which SecureDrops have significant landing page issues (e.g., use of Google Analytics). This command is run as a cron job and the result is published to http://securedrop.org/media/documents/scanresults.csv (we've never announced that URL, but it is referenced e.g. in #532). 

This is adding to the technical complexity of SecureDrop.org, and we may temporarily lose this CSV as part of the migration to k8s. If possible, it would be good to make the latest scan result available via the directory API, as we do for SecureTheNews.

**Comment by harrislapiroff** [comment]
This looks good and shouldn't be too tricky. Marking it as ready for dev!
