### ISSUE TITLE
Discourse post get URL is too long

### ISSUE THREAD

**Issue by maeve-fpf** [freedomofpress/securedrop.org#740]
In https://github.com/freedomofpress/securedrop.org/blob/develop/search/utils/discourse/client.py#L79, we build a URL to request from Discourse from every post in a given topic. Discourse is currently returning `413 Client Error: Payload Too Large for url: https://forum.securedrop.org/latest.json` for at least one of these requests (it's a GET, so it technically should be 414, but this is reasonable).

I'm not sure if the actual limit is documented somewhere, but there should be some sort of cap on how many query params we put in a URL (or the length of the joined string), which will mean multiple requests if we do need all results.

**Comment by conorsch** [comment]
For the Wagtail sites, we raise the `client_max_body_size` to ~10MB, so folks can upload images and such.

We _aren't_ setting the same on discourse, so maybe try that first? It's not clear to me whether the length of the URL counts toward payload or is determined by a separate value, but call me optimistic.

**Comment by eloquence** [comment]
Closed via #800.
