### ISSUE TITLE
Remove onion address setting from database

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/securedrop.org#742]
Instead of pulling the onion address from the database, we should pull it from settings. Check with @maeve-fpf for the name of the env var that stores the address

**Comment by maeve-fpf** [comment]
The env var is `DJANGO_ONION_HOSTNAME` - see https://github.com/freedomofpress/securethenews/pull/271 for how I added it to settings there. That PR includes the HTML link for the footer, which is already there on securedrop.org - I assume updating how the code determines the hostname will fix it automatically.
