### ISSUE TITLE
502 reported on docs.securedrop.org [cannot repro]

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop.org#765]
On Oct 30 at 21:43 ET, a contributor reported that docs.securedrop.org had been unreachable for about 40 minutes, and they were consistently getting a 502. Another contributor mentioned having issues loading docs.securedrop.org on Oct 28th. Cannot reproduce but filing for historical purposes/in case relevant.

cc @ketudb

**Comment by kushaldas** [comment]
readthedocs had some issues in the last week iirc. I am guessing that is the cause.

**Comment by eloquence** [comment]
Yep, outage report here: https://twitter.com/readthedocs/status/1322194633586167808 - resolved upstream
