### ISSUE TITLE
Make SDO settings consistent with other apps

### ISSUE THREAD

**Issue by maeve-fpf** [freedomofpress/securedrop.org#778]
There are a few quirks in each app's settings that we'd like to make a little more unified. Things we can do on SDO:

- Adjust how CSP variables like `DJANGO_CSP_*_HOSTS` are used: variable should contain the full entry (with `https://`), and if possible, consolidate the vars into one. Other apps should follow the example here.
- Instead of `DJANGO_LOG_CONSOLE` and `DJANGO_LOG_PATH`, just log to console if a log path is not set. Don't require `DJANGO_LOG_JSON`, default it appropriately.
- Treat env vars that should be "booleans" the same everywhere.

**Comment by maeve-fpf** [comment]
Additional note here: we did not add `DJANGO_LOG_JSON` at all, so upgrade `python-json-logger` to 0.1.11 to match STN while fixing this.

**Comment by SaptakS** [comment]
@maeve-fpf @harrislapiroff this issue can be closed?

**Comment by eloquence** [comment]
Closed per web sync today.
