### ISSUE TITLE
Create form option for onion name in SecureDrop directory entry

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop.org#782]
Now that we have [onion names](https://securedrop.org/news/introducing-onion-names-securedrop/), it would be good to show them in an instance's directory entry. We should show both the onion name and the 56-char v3 url, to reinforce that both are valid for an instance.

Not every instance will have an onion name, so it should be an optional field.

Happy to provide more details as needed!

**Comment by eloquence** [comment]
We'll have to decide how to change the text on the directory entry. Right now the blab goes as follows:

> If you intend to submit information to [x]'s SecureDrop, we recommend that you compare the .onion address provided on the organization’s landing page to this one `reallylong.onion` and verify that the addresses match before continuing. This provides a strong layer of defense against certain types of attacks that might try to trick you into visiting a malicious SecureDrop instance masquerading as a legitimate one. We recommend reading the Source Guide for more comprehensive documentation on SecureDrop usage and risks. 

That language could use a refresh along the way as it's currently at risk of exceeding the tl;dr threshold for sources.

**Comment by rocodes** [comment]
A followup note that this property should be part of the api as well!

**Comment by rocodes** [comment]
@eloquence: what about

> Be sure that the .onion address provided on [X's] landing page below matches
>  `v3.onion` 
> [or `onionname.onion`] 
> before continuing. This helps ensure you are visiting a legitimate SecureDrop instance. We recommend reading the Source Guide for more comprehensive documentation on SecureDrop usage and risks.

with the [or `onionname`] part only being included if the org has an onion name ofc.

**Comment by eloquence** [comment]
SGTM, perhaps shorten this bit even further:

> We recommend reading the Source Guide for more comprehensive documentation on SecureDrop usage and risks.

to:

> See our Source Guide for more information on SecureDrop usage and risks.

For cross-reference, @ninavizz proposed a more comprehensive redesign/rewrite in #642, but I think that goes beyond the scope of this issue.

**Comment by SaptakS** [comment]
Just to be sure, the onion names will be added manually for the directory entry pages from admin? or is there some other way of detecting whether an org has onion name? cc @eloquence @rocodes

**Comment by eloquence** [comment]
Hi @SaptakS, great question! If we wanted to be clever, we could try to look up the existence of an onion name using our own signed ruleset at https://securedrop.org/https-everywhere/ .  That would strike me as problematic, though, in that we generally treat the directory as a _source_ of truth, not as a _sink_ for information received from elsewhere.

I think for now it's simplest to just add a form field, and we can consider workflow automation in either direction further down the line (@harrislapiroff @conorsch please jump in if you disagree).

**Comment by conorsch** [comment]
That sounds right to me: a new model field, which will be unset in most cases, and that populates the API entry for a given instance. At some point we can update the scan logic to include pulling from the rulesets, but these updates are far from high-traffic, so I don't think that's necessary at this point in time.

**Comment by SaptakS** [comment]
Makes sense to me. Thanks for clearing that up.
