### ISSUE TITLE
500 when attempting to add new SecureDrop Directory entry

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop.org#788]
hi folks! 
I am encountering an error when I try to add a new directory entry in Wagtail. 

STR:
Log in, navigate to Pages > Directory > Add child page (https://securedrop.org/admin/pages/19/add_subpage/ ) > select "Directory entry".
Expected: directory entry template visible, able to fill in.
Actual: 500 on `https://securedrop.org/admin/pages/add/directory/directoryentry/19/`

Edited to add: the "create form page" option on the same page does not produce this error.

**Comment by eloquence** [comment]
Thanks @rocodes, am able to reproduce, error occurs before even the form is loaded, may be a recent regression since that form was previously loading fine.
