### ISSUE TITLE
CSP error and wagtail button visual error (related?)

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop.org#810]
In testing the new Wagtail version on staging.securedrop.org, I am noticing the following CSP failure in Firefox, which may be the cause of some minor stylistic differences I'm observing (e.g., the Freedom of the Press Foundation link in the footer is blue instead of white, and the Wagtail admin bird in the bottom right is trying to escape its surrounding circle):

> Content Security Policy: The page’s settings blocked the loading of a resource at inline (“style-src”).

**Comment by harrislapiroff** [comment]
The link colors were resolved in #812 but the CSP errors and the bird escaping the button are still happening.

![image](https://user-images.githubusercontent.com/296631/109051323-67069500-76a8-11eb-8ec8-78593be10570.png)

**Comment by SaptakS** [comment]
Seems that CSP is related to an inline style that was added in wagtail related to that bird button visual. So I guess they are related.
