### ISSUE TITLE
Form submission on staging.securedrop.org results in error 500

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop.org#811]
Attempting to submit https://staging.securedrop.org/help/ results in an error 500. I expect our ticket system integration isn't working here, but we should probably handle any prod differences more gracefully so we can distinguish expected and unexpected behavior.

**Comment by eloquence** [comment]
I observed that a simple test form created from scratch could be submitted successfully, so the issue may be specific to the email/ticket integration with that form.

**Comment by harrislapiroff** [comment]
I'm guessing this is going to show up in logs as a mailgun API error (and that the form is directing to an address that's not on our mailgun sandbox allowlist) but we should verify.

**Comment by harrislapiroff** [comment]
Confirmed my theory. Switching the email recipient for that form to one on our mailgun sandbox list made submission work without a 500. Closing.
