### ISSUE TITLE
Internal server error when visiting preview URL

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop.org#818]
This is less dramatic than it sounds, because these URLs are generally not meant be shareable as I understand it, but they probably also shouldn't be throwing a 500. That is however what I get when visiting https://securedrop.org/admin/pages/220/edit/preview/ after authenticating.

**Comment by eloquence** [comment]
(Now that the page has been published, I can no longer reproduce the issue at that URL, so it may only arise in some cases during drafting/preview by another user.)

**Comment by chigby** [comment]
Is it possible to post (or link to) more information about the particular error?

**Comment by eloquence** [comment]
It was just `Internal server error` followed by a blank page. Let's see if we can catch it in staging. I created a draft  at https://staging.securedrop.org/admin/pages/211/edit/preview/ - is that page viewable for you, or does it show an error?

If we can't repro it, it may be worth poking at the logs to see if we can still dig up the error from yesterday.

**Comment by harrislapiroff** [comment]
Hm, I get what appears to be a semi-appropriate error page on both sites

![Screen Shot 2021-03-18 at 16 13 32](https://user-images.githubusercontent.com/296631/111691643-e64d3b80-8804-11eb-9a5a-30ae6ae56d53.png)

**Comment by eloquence** [comment]
Can no longer reproduce, closing for now.
