### ISSUE TITLE
Publish new signing key

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop.org#851]
We are planning to [rotate the SecureDrop signing key](https://github.com/freedomofpress/securedrop/issues/5923) as part of the SecureDrop 2.0.0 release, currently scheduled for June 15. The key fingerprint and contents will change. We will need to update any places on the SecureDrop website that refer to the old key, most notably, the site footer (editable via Settings -> Site footer).

**Comment by soleilera** [comment]
@eloquence I believe this has been done and can be closed

**Comment by eloquence** [comment]
Right you are!
