### ISSUE TITLE
Add warning status for landing page reachability issues

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop.org#931]
We recently encountered an issue with a SecureDrop directory entry whose landing page was persistently unreachable. We unpublished the directory entry, which resulted in follow-up breakage with its [onion name ruleset](https://github.com/freedomofpress/securedrop-https-everywhere-ruleset/) entry. In a nutshell, if a directory entry is unpublished, its onion name must also be removed at the same time.

As a less severe measure, it would be good if we at least had a severe (red) warning message for landing pages that are erroring out or not reachable (similar to our other severe warning statuses for landing pages). Ideally, it would be possible to set this status manually and to have the scanner detect common error statuses (4xx, 5xx, etc.).

The point would be to inform sources that we're aware that the landing page is not reachable, and that they should take extra caution because it means that an important verifiability layer has gone missing. Suggested placeholder text for now (we can refine):

> This SecureDrop's landing page appears to be unreachable. You may wish to wait until the landing page is back online before contacting this SecureDrop, so you can verify the .onion address.

**Comment by chigby** [comment]
Is this a situation where we want the text to be customizable by the admin?
