### ISSUE TITLE
Python easy dependency updates

### ISSUE THREAD

**Issue by SaptakS** [freedomofpress/securedrop.org#951]
Update the following packages to their latest versions:

- [x] bleach | 4.1.0 | 5.0.1 |
- [x] django-anymail | 8.4 | 8.6 |  
- [x] django-modelcluster | 5.2 | 6.0 | 
- [x] django-storages | 1.12.3 | 1.13.1 |  
- [x] django-webpack-loader | 1.4.1 | 1.6.0 |  
- [x] djangorestframework | 3.12.4 | 3.13.1 |  
- [x] wagtail-factories | 2.0.1 | 3.1.0 |  
- [x] feedparser | 6.0.8 | 6.0.10 |  
- [x] psycopg2 | 2.8.6 | 2.9.3 |  
- [x] pygments | 2.10.0 | 2.12.0 |  
- [x] tldextract | 3.1.2 | 3.3.1 |  
- [x] tinycss2 | 1.1.0 | 1.1.1 |  
- [x] unittest-xml-reporting | 3.0.4 | 3.2.0 |  
- [ ] django-allauth | 0.47.0 | 0.51.0 |  
- [ ] django-allauth-2fa | 0.8 | 0.10.0 |  
- [x] requests | 2.26.0 | 2.28.1 |  
- [x] urllib3 | 1.26.10 | 1.26.11 |  
- [x] wagtailmedia | 0.8.0 | 0.10.1 |  
- [x] whitenoise | 5.3.0 | 6.2.0

Remove the following packages:
- [x] Pillow
- [x] PyOpenSSL

Also:
- [x] Remove the pinning on structlog and update.

**Comment by chigby** [comment]
django-allauth and django-allauth-2fa have already been removed as dependencies.
